base_url = "https://soramimi.netlify.app/"
title = "空耳创世纪"
theme = "mikoto"
description = ""
compile_sass = true
slugify-path = true
highlight_code = true
highlight_theme = "monokai"
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
    # {name = "series", rss = true},
]

[extra]
copyright = true
author = "无名酱"
mikoto_title = "空耳创世纪"
mikoto_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    # {url = "$BASE_URL/series", name = "Series"},
    {url = "$BASE_URL/about", name = "About"},
]

favicon = "https://github.com/GalAster/sora.github.io/blob/master/static/avatar.jpg"
github_link = "https://github.com/GalAster/Soramimi"

aplayer_enable = true

